run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec

linters-settings:
  goimports:
    local-prefixes: github.com/nikicat/gopass-secret-service

  gosec:
    excludes:
      - G104  # Unhandled errors (too noisy for D-Bus code)
      - G115  # Integer overflow - Unix timestamps won't overflow uint64

  errcheck:
    exclude-functions:
      # D-Bus Export/Emit calls where errors are non-critical
      - (*github.com/godbus/dbus/v5.Conn).Export
      - (*github.com/godbus/dbus/v5.Conn).Emit

issues:
  exclude-rules:
    # Ignore long lines in test files
    - path: _test\.go
      linters:
        - lll

    # Ignore unused parameters in interface implementations
    - linters:
        - unparam
      text: "always receives"
